ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "shippingCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "taxCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "shippingStatus" TEXT DEFAULT 'NOT_SHIPPED',
ADD COLUMN IF NOT EXISTS "trackingNumber" TEXT;
